// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxdynPhhcgtIz5eyaAgwuS5xeF4sjvFZk',
    appId: '1:249940824315:web:7ea3a2fa649338ae49a05e',
    messagingSenderId: '249940824315',
    projectId: 'mutiuojo-54f46',
    authDomain: 'mutiuojo-54f46.firebaseapp.com',
    storageBucket: 'mutiuojo-54f46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXweWfVDO168Eupm-ixpT2E4kDa-ZROkk',
    appId: '1:249940824315:android:44af6d43942b09b949a05e',
    messagingSenderId: '249940824315',
    projectId: 'mutiuojo-54f46',
    storageBucket: 'mutiuojo-54f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy0WAgZZ1CalJStDoQ4hfjnQBU7FRFPdE',
    appId: '1:249940824315:ios:1c5667c56a29ebc349a05e',
    messagingSenderId: '249940824315',
    projectId: 'mutiuojo-54f46',
    storageBucket: 'mutiuojo-54f46.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy0WAgZZ1CalJStDoQ4hfjnQBU7FRFPdE',
    appId: '1:249940824315:ios:1c5667c56a29ebc349a05e',
    messagingSenderId: '249940824315',
    projectId: 'mutiuojo-54f46',
    storageBucket: 'mutiuojo-54f46.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxdynPhhcgtIz5eyaAgwuS5xeF4sjvFZk',
    appId: '1:249940824315:web:aa98f597b7d0e25049a05e',
    messagingSenderId: '249940824315',
    projectId: 'mutiuojo-54f46',
    authDomain: 'mutiuojo-54f46.firebaseapp.com',
    storageBucket: 'mutiuojo-54f46.firebasestorage.app',
  );
}
